name: Turtle Studios
favicon: null
layout_spectrum: 0.48229
typography_spectrum: 0.24106
title: 'Turtle Studios | music production | recording | licensing | mastering'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141414'
    - '#49873a'
    - '#4b4b4b'
    - '#9a9a9a'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
